AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable

Layout/LineLength:
  Max: 80
  Exclude:
    - log_auditor.gemspec

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
