name: Ruby pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - uses: actions/cache@v2
      env:
        cache-name: cache-rails-deps
      with:
        path: /usr/local/bundle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

    - name: Build deps
      run: |
        gem install bundler
        bundle install

    - name: Run Linter (Rubocop)
      run: |
        bundle exec rubocop --format json -o report.json

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - uses: actions/cache@v2
      env:
        cache-name: cache-rails-deps
      with:
        path: /usr/local/bundle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-

    - name: Build deps
      run: |
        gem install bundler
        bundle install

    - name: Run specs
      run: |
        bundle exec rspec --fail-fast
